### 1. Import libraries

In [37]:
import pandas as pd

### 2. Read data

In [38]:
train_df = pd.read_csv('../../data/titanic_train.csv')
train_df[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

### 3. Checking Dimensions of Data

In [39]:
print("Training Dataset shape is: ", train_df.shape)

Training Dataset shape is:  (891, 12)

### 4. Checking Data types

In [40]:
print("Data Types of Training Data is: \n")
print(train_df.dtypes)

Data Types of Training Data is:

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [41]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [42]:
train_df.index

RangeIndex(start=0, stop=891, step=1)

In [43]:
train_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

### 5. Checking Duplicates Data

In [44]:
print(f"Duplicates in Train Dataset is: {train_df.duplicated().sum()} ({100 * train_df.duplicated().sum() / len(train_df)}%)")

Duplicates in Train Dataset is: 0 (0.0%)

In [45]:
row_to_duplicate = train_df.iloc[[-1]]
df_new = pd.concat([train_df, row_to_duplicate], ignore_index=False).reset_index(drop=True)

In [46]:
print(f"Duplicates in the new Dataset is: {df_new.duplicated().sum()} ({100 * df_new.duplicated().sum() / len(df_new)}%)")

Duplicates in the new Dataset is: 1 (0.11210762331838565%)

In [47]:
# duplicated showing after the 2nd occurrence!

df_new[df_new.duplicated()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [48]:
df_new[df_new.duplicated(keep=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q
891,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [49]:
# This will show the ORIGINAL row (the first one)

df_new[df_new.duplicated(keep='last')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [54]:
df_new = df_new.drop_duplicates()

In [57]:
print("Number of duplicates:", df_new.duplicated().sum())

Number of duplicates: 0