In [2]:
import pandas as pd

df = pd.read_csv('../../data/titanic_train.csv')

In [3]:
# Show data

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Calculate the Mean

df['Age'].mean()

np.float64(29.69911764705882)

In [5]:
# Calculate the Median

df['Age'].median()

np.float64(28.0)

In [6]:
# Calculate the Mode

df['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [7]:
# Calculates the count or frequency of non-null values

df['Ticket'].count()

np.int64(891)

In [8]:
# Standard Deviation

df['Age'].std()

np.float64(14.526497332334042)

In [9]:
df['Fare'].std()

np.float64(49.6934285971809)

In [10]:
# Min, Max

df['Age'].min(), df['Age'].max()

(np.float64(0.42), np.float64(80.0))

In [11]:
# Summarizes general descriptive statistics

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
# Aggregating statistics grouped by category

# - Split the data into groups
# - Apply a function to each group independently
# - Combine the results into a data structure

df[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [14]:
# Count number of records by category

df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [15]:
df.groupby("Pclass")["Pclass"].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64